 export  {default as Navbar} from "./navbar/navbar"
 export {default as Slider } from  "./slider/slider"
 export {default as  Home} from "./Pages/Home"
 export { default as NavbarTop} from  "./navbar/navbar_top"
 export {default as BaseInfo} from "./base-info/base-info"
 export { default as SliderSmall} from  "./slider-small/slider-small"
 export { default as Footer}  from "./footer/footer"
 export { default as CheapGoods} from "./cheap goods/cheap-goods"
 export {default as ToRecommend}  from "./to recommend/to-recommend"
 export { default as ProductSlider} from "./single-product-slider/product-slider"
  export { default as Brend} from "./brend/brend"
  export { default as Category}  from "./category/category"